name: Run Python Script

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour, you can adjust the cron schedule as needed
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: List files in root directory
        run: ls -la
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Add any other dependencies your script requires
      - name: Run script
        run: python dune_data.py  # Replace 'dune_data.py' with the path to your Python script
