name: Run Python Scripts

on:
  schedule:
    - cron: '0 */3 * * *'  # Runs every 3 hours
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Add any other dependencies your script requires
      - name: Run dune_data.py
        run: python dune_data.py
      - name: Run dune_data2.py
        run: python dune_data2.py
      - name: Run dune_data3.py
        run: python dune_data3.py
      - name: Run dune_data4.py
        run: python dune_data4.py
      - name: Run dune_data5.py
        run: python dune_data5.py
